-- Migration: Create AI Chat Metrics Table
-- Database: postgres://cocoindex:cocoindex@localhost/cocoindex
-- Created: 2025-12-05
--
-- This table stores every AI response with token metrics.
-- User feedback (rating) is updated separately via message_id.

-- Drop old feedback table if exists (optional - comment out if you want to keep historical data)
-- DROP TABLE IF EXISTS ai_chat_feedback;

-- Table to store AI chat metrics and feedback
CREATE TABLE IF NOT EXISTS ai_chat_metrics (
    id SERIAL PRIMARY KEY,
    message_id VARCHAR(100) UNIQUE NOT NULL,  -- UUID from frontend for updates
    user_question TEXT NOT NULL,
    ai_response JSONB NOT NULL,               -- Full AI response as JSONB
    dcid VARCHAR(50) NOT NULL,
    user_email VARCHAR(255) NOT NULL,

    -- Token metrics as separate columns for easy querying
    input_tokens INT DEFAULT 0,
    output_tokens INT DEFAULT 0,
    cache_read_input_tokens INT DEFAULT 0,
    cache_creation_input_tokens INT DEFAULT 0,
    cost_usd DECIMAL(10, 6) DEFAULT 0,

    -- User feedback (updated later)
    rating VARCHAR(10) CHECK (rating IS NULL OR rating IN ('good', 'bad')),
    feedback_text TEXT,
    feedback_at TIMESTAMP WITH TIME ZONE,

    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index on message_id for fast lookups when updating feedback
CREATE INDEX IF NOT EXISTS idx_ai_chat_metrics_message_id ON ai_chat_metrics(message_id);

-- Index on dcid for filtering by organization
CREATE INDEX IF NOT EXISTS idx_ai_chat_metrics_dcid ON ai_chat_metrics(dcid);

-- Index on created_at for time-based queries
CREATE INDEX IF NOT EXISTS idx_ai_chat_metrics_created_at ON ai_chat_metrics(created_at DESC);

-- Index on rating for filtering feedback
CREATE INDEX IF NOT EXISTS idx_ai_chat_metrics_rating ON ai_chat_metrics(rating);

-- GIN index on JSONB for querying response content
CREATE INDEX IF NOT EXISTS idx_ai_chat_metrics_response ON ai_chat_metrics USING GIN (ai_response);

-- Comments
COMMENT ON TABLE ai_chat_metrics IS 'Stores AI chat metrics (tokens, cost) and user feedback for Talk to Data feature';
COMMENT ON COLUMN ai_chat_metrics.message_id IS 'Unique message ID from frontend (UUID) for updating feedback';
COMMENT ON COLUMN ai_chat_metrics.user_question IS 'The question the user asked';
COMMENT ON COLUMN ai_chat_metrics.ai_response IS 'Full AI response as JSONB (content, sql, queryResult, etc.)';
COMMENT ON COLUMN ai_chat_metrics.dcid IS 'Organization/DC identifier';
COMMENT ON COLUMN ai_chat_metrics.input_tokens IS 'Input tokens used by LLM';
COMMENT ON COLUMN ai_chat_metrics.output_tokens IS 'Output tokens generated by LLM';
COMMENT ON COLUMN ai_chat_metrics.cache_read_input_tokens IS 'Tokens read from cache';
COMMENT ON COLUMN ai_chat_metrics.cache_creation_input_tokens IS 'Tokens used to create cache';
COMMENT ON COLUMN ai_chat_metrics.cost_usd IS 'Estimated cost in USD';
COMMENT ON COLUMN ai_chat_metrics.rating IS 'User rating: good, bad, or NULL if not rated';
COMMENT ON COLUMN ai_chat_metrics.feedback_text IS 'Optional text feedback from user';
COMMENT ON COLUMN ai_chat_metrics.feedback_at IS 'Timestamp when user provided feedback';
COMMENT ON COLUMN ai_chat_metrics.user_email IS 'User email address';
